title: <p align = "center>" Vineet Juneja </p>
logo: /assets/img/logo.png
description: 
<p align = "center>"
Minimal is a theme for GitHub Pages.

</p>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
